FROM cypress/browsers:chrome69
COPY . /cypress
WORKDIR /cypress
RUN npm install @cypress/webpack-preprocessor@4.1.0 cypress@3.6.0 ls@0.2.1 mocha@5.2.0 mochawesome@4.1.0 mochawesome-merge@2.0.1 rimraf@3.0.0 ts-loader@6.2.1 typescript@3.6.4 uuid@3.3.2 webpack@4.41.2 yargs@14.2.0